# DO NOT USE THIS FILE AS-IS IN PRODUCTION
# This is a template for creating secrets. Use this as a guide to create secrets using:
# - kubectl create secret
# - Sealed Secrets
# - External Secrets Operator
# - Vault
# - or your preferred secrets management solution

apiVersion: v1
kind: Secret
metadata:
  name: tuya-alarm-secrets
type: Opaque
stringData:
  tuya-access-id: "YOUR_TUYA_ACCESS_ID"
  tuya-access-secret: "YOUR_TUYA_ACCESS_SECRET"
  tuya-endpoint: "https://openapi-sg.iotbing.com"